server:
  port: 8082

oauth2-server-url: http://localhost:8084
security:
  oauth2:
    client:
      client-id: client
      client-secret: client
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwk:
        key-set-uri: ${oauth2-server-url}/oauth/token_key
spring:

  datasource:
    url: jdbc:postgresql://localhost/db_oshop
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  application:
    name: product-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
    database: 0

feign:
  client:
    config:
      user-service:
        readTimeout: 10000
        connectTimeout: 10000





